### ISSUE TITLE
split #graphics off of #game-dev

### ISSUE THREAD

**Issue by Lokathor** [rust-community-discord/non-binding-issue-discussions#3]

**Comment by troiganto** [comment]
Current status: #game-dev has been renamed to #game-and-graphics-dev, we'll see how this will go. If there still are issues with this double-usage, we might come back to the idea of splitting them

**Comment by troiganto** [comment]
Motivation according to @rep-nop :
> there's often overwhelming discussion of graphics related tangents that shadow other discussion

**Comment by mooman219** [comment]
@troiganto's quote of me is pretty much the gist of the issue. If we decided not to split then it's not a big deal in reality.

---

Outside of #general and #beginners, the gamedev channel is one of the most frequented channels on the server. I think it would be a good idea to embrace that and allow for more targeted discussion.

For reference, under Rust Extra, #game-and-graphics-dev has the most usage. Second place is #lang-dev . #game-and-graphics-dev has about 7 times the message count of #lang-dev

#windows-dev was created from #os-dev, which has roughly 13% the usage as #game-and-graphics-dev and still warranted a split.

---

Example situation #1 of a user getting drowned out: https://discordapp.com/channels/273534239310479360/335502453371961344/589566686730911744
I made a note to get back to them after our discussion and pinged them afterwards.

**Comment by troiganto** [comment]
[another example of contention](https://discordapp.com/channels/273534239310479360/335502453371961344/588144781734051878)

[some prior discussion](https://discordapp.com/channels/273534239310479360/585158846092148757/588479979906531352)

**Comment by troiganto** [comment]
Broken down to messages per day:

Channel | Messages/Day
--------|-------------
RUST GENERAL / MISC |
offtopic | 587
general | 482
beginners | 454
RUST EXTRA |
game-and-graphics-dev | 435
lang-dev | 72
windows-dev | 46
net-and-webdev | 43
embedded-dev | 21
gui-and-ui-dev | 16
os-dev | 5
crypto-and-security-dev | 5
science-and-ai-dev | 5
emu-dev | 5

Messages generally are taken from 2019-01-01 to 2019-06-17, for `#windows-dev` from 2019-05-29 to 2019-06-17.

**Comment by mooman219** [comment]
Potential channel description for #graphics via DeltaPHC

> Graphics: using graphics APIs and rendering techniques. GL, Vulkan, DX, and how to apply them

**Comment by rep-nop** [comment]
It is worth noting as moxian pointed out (https://discordapp.com/channels/273534239310479360/461038099682689054/590330316984549399) that if we can't come to a consensus with what's related to graphics and what's not, maybe splitting it out into ~3 or so channels could be an option. I think lumping in #gui-and-ui-dev with it could also make sense as well.

**Comment by icefoxen** [comment]
I'm tentatively in favor but would like to present an alternative interpretation of the statistics for consideration: the game-dev channel gets a lot of traffic 'cause there's lots of cool people there that make a good and chatty community. That's the main reason I hang out there, at least.

It would be interesting to split it into game and graphics dev, wait a while, and then see what the new statistics look like.

**Comment by troiganto** [comment]
Just collecting a few opinions that have been uttered over the course of the day so we won't lose them.

@troiganto 
> After sleeping on it for a bit, it seems like the best next step would be to split graphics out of gamedev and declare gamedev to be for everything relating to creating games in rust.
>
> We know how people work: even after the split, there will be graphics questions in the gamedev channel and in moderation, that's okay. In fact, if 90% of questions pre-split are about graphics,a slight overlap might actually make the traffic be a bit more balanced.
> 
> Once both channels have been separate for two weeks or so, we can have another look at the message numbers and decide further steps
>
>Regarding game design specifically, i see no reason to prohibit it a priori as long as it's vaguely related to rust the language. Should this point turn out to be a problem, we can still make a decision at a later point in time

@rep-nop's reply:
> I think that's a pretty good way to go about it. Doesn't complicate things any further really and should hopefully give people the results they want

Me summarizing @moxian's point of view:
> I also agree with mox that this looks s lot like two parties using different definitions of "game design"
> Moxi uses it in the sense of "how many adventurer classes should my awesome rpg have"
> Other people seem to use it like "how should i model adventurers as objects in my type system"
> Which moxi in turn defined as "game architecture". Did i get that right @moxian::bikeshed() ?

to which they replied:
> @pen  yep
> In my extensive time spent on gaming forums (mtg, league of legends, overwatch, heroes of the storm primarily) I've seen the term used a lot and always in the sense of "how should we design our cards/characters/maps/abilities/progression/whatever to be fun to play"

@Lokathor's objection:
> Do people actively want a split? From what I read in the gamedev channel the subject was murky at best. In my eyes, the only people who think there's any problem at all are the kind of people who try to police others and enforce some notion that the names of channels must somehow exactly match what the channels are actually used for. While that's nice in theory, it's really not important at all. A person new to the server might be confused for a tiny bit, but they figure it out pretty quickly.
>
> In conclusion: what we need is for the very small number of people trying to police topics to chill way out because it's actually them who are the problem

Then later:
> i'm fine with a split as long as the topics of the split channels are kept very broad because basically i want less channel topic policing so i'd prefer every channel to be about as broad as possible

A few other statements I've collected non-representatively:

> fn thezoq2(_: 🍈, _: impl 🗡) → 🍉: I would like to see a split, because the traffic is just too large for me to keep up with, despite me being somewhat interested in the topic [Editor's note: they want a channel for just graphics so they can mute the game dev one]

> unsafe extern crate winapi as 🐇;: For me it isn't about policing topics, it is about gamedev being such a popular channel

> /*Mathy*/println!("Pride");: I am not sure how many of these are there but game devs who are low level graphics newbies who feel kinda overwhelmed with all the gfx-hal/renderers talk in #game-and-graphics-dev or get flooded by an ongoing graphics discussion are the main reason for a split, to me

**Comment by troiganto** [comment]
Two more options which haven't managed to garner a lot of support so far:
- two channels that may both be used for graphics *and* gamedev
    - counter point: people who are interested in only one topic have to follow both channels
- splitting into game-development and game-engine-development
    - counter point: the lines between these topics are even blurrier than between graphics and gamedev

It has been stressed that if we split into graphics and gamedev, graphics questions could still be asked in the gamedev channel, as long as they don't crowd out other discussions.

**Comment by troiganto** [comment]
Current status: no complaints about the #game-and-graphics-dev channel have been raised since the last comment

**Comment by mooman219** [comment]
Things died down and no one has complained in a while. Motion to close issue.
