### ISSUE TITLE
Semi-Private Discussion channel

### ISSUE THREAD

**Issue by troiganto** [rust-community-discord/non-binding-issue-discussions#6]
## Proposal

- The #governance channel gets renamed to #council-discussion
- every member can *read* the channel, but only councilmembers (and staff) can write in it
- the purpose is to keep discussions between councilmembers focused

## Disadvantages

- the discussion might get disjointed if regular members in #meta comment on things said in #council-discussion and a council member has to reply to this comment
- there does not seem to be a need for such a channel considering the low frequency of messages in #meta 

## Alternatives

- archive #governance and use #meta for fully public discussions

## Opinion
- @troiganto: vaguely in favor of it, but I would not mind the alternative either
- @Lokathor: agrees with this so that he doesn't have to go looking in the PMs pile again
- @rep-nop: ???
- @deltaphc: ???
- @serentty: ???

**Comment by Lokathor** [comment]
@lokathor agrees with this so that he doesn't have to go looking in the PMs pile again

**Comment by troiganto** [comment]
Closing this since the current setup is working well enough: #meta for public discussions and a private chat where moderators can discuss sensitive issues with the council. No decision making happens in the private chat.
